### ISSUE TITLE
FTP files changed or all files option

### ISSUE THREAD

**Issue by pgschr** [sebastianpopp/git-ftp-action#8]
`git diff --name-only HEAD~` gives you the list of files changed in the last commit, can you add the option of either files changed or all files (default)?

**Comment by sebastianpopp** [comment]
git-ftp always uploads just the files changed. I don't think it makes sense for this action to offer an option for all files to be uploaded since that is something people would do with just regular ftp (there are actions for that as well [here](https://github.com/marketplace/actions/ftp-action) and [here](https://github.com/marketplace/actions/ftp-deploy)).
